version: '3.7'

services:
    db:
        container_name: database-tldv
        image: mysql
        restart: always
        command: >
            --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=tldv
            - TZ=America/Sao_paulo
        volumes:
            - mysql:/var/lib/mysql

    app:
        build: .
        container_name: app-tldv
        ports:
            - '3000:3000'
        volumes: 
            - .:/usr/app
        links: 
            - db
        depends_on: 
            - db 

volumes:
    mysql:
        driver: local